version: '3.7'

networks:
  dbnetwork:

services:
  db:
    image: postgres
    container_name: db
    restart: always
    networks:
      - dbnetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinhabackend
    volumes:
      - ./scripts/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "200GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 25s

  adminer:
    image: adminer
    restart: always
    networks:
      - dbnetwork
    links:
      - db
    ports:
      - 8080:8080
